// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_CrkoxkCxf6HVWh3qIHyQxcsOxYVw8w',
    appId: '1:1079365988559:web:f08ed30d9b6f26dc3ac7ba',
    messagingSenderId: '1079365988559',
    projectId: 'mikhunchikapp',
    authDomain: 'mikhunchikapp.firebaseapp.com',
    storageBucket: 'mikhunchikapp.firebasestorage.app',
    measurementId: 'G-GHKDW19BXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq7kfdwuU3JRv0HD-3np68Y808vFGIeCg',
    appId: '1:1079365988559:android:c51975f6afedb3763ac7ba',
    messagingSenderId: '1079365988559',
    projectId: 'mikhunchikapp',
    storageBucket: 'mikhunchikapp.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLxtKeT8MEkptTK4owicoDArpe0ykF9ZU',
    appId: '1:1079365988559:ios:b217e44ebb5e298c3ac7ba',
    messagingSenderId: '1079365988559',
    projectId: 'mikhunchikapp',
    storageBucket: 'mikhunchikapp.firebasestorage.app',
    iosBundleId: 'com.example.mikunchik',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLxtKeT8MEkptTK4owicoDArpe0ykF9ZU',
    appId: '1:1079365988559:ios:b217e44ebb5e298c3ac7ba',
    messagingSenderId: '1079365988559',
    projectId: 'mikhunchikapp',
    storageBucket: 'mikhunchikapp.firebasestorage.app',
    iosBundleId: 'com.example.mikunchik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx_CrkoxkCxf6HVWh3qIHyQxcsOxYVw8w',
    appId: '1:1079365988559:web:75e1614dcb8512343ac7ba',
    messagingSenderId: '1079365988559',
    projectId: 'mikhunchikapp',
    authDomain: 'mikhunchikapp.firebaseapp.com',
    storageBucket: 'mikhunchikapp.firebasestorage.app',
    measurementId: 'G-F1GEY2TTS8',
  );

}